version: 2.1

jobs:
  build-socat:
    docker:
      - image: docker:18.09
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker build --progress plain -f socat/Dockerfile socat/
  build-tiny:
    docker:
      - image: docker:18.09
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker build --progress plain -f tiny-build/Dockerfile tiny-build/
  build-go:
    docker:
      - image: docker:18.09
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker build --progress plain -f go-build/Dockerfile go-build/
  build-node:
    docker:
      - image: docker:18.09
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3

      - run: docker build --progress plain -f node-build/Dockerfile node-build/
  build-py:
    docker:
      - image: docker:18.09
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker build --progress plain -f py-build/Dockerfile py-build/

workflows:
  docker-build:
    jobs:
      - build-socat
      - build-tiny
      - build-go
      - build-node
      - build-py
